### ISSUE TITLE
Bug related to `dark-theme`

### ISSUE THREAD

**Issue by devsubid** [omidnikrah/profile-activity-generator#8]
whenever switching the theme the `background: linear-gradient` in 
```HTML
<ul id="how-to-use">
      <li>Click on the squares to change the colors</li>
      <li>Press Ctrl key and hover on the squares to change the colors</li>
</ul>
```

```CSS
#how-to-use {
    margin: 60px 0 0;
    list-style: none;
    padding: 30px 45px;
    border-radius: 10px;
    background: linear-gradient(180deg, rgba(246,246,246,1) 0%, rgba(246,246,246,0) 100%);
    position: relative;
}
```
 is weirdly reacting
<br><br>

**Screenshot**
![image_2022-08-19_130343291](https://user-images.githubusercontent.com/85873704/185567728-3893d8c9-8b40-4396-bf0d-d797b0e42cfc.png)
